name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  PrintProcessingVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js Version
        run: node --version
      - name: Print React.js Version
        run: npx create-react-app --version # React is typically managed by Node.js, so we check its version this way

  PrintDatabaseVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Install MongoDB
        run: |
          sudo apt-get update
          sudo apt-get install -y mongodb
      - name: Print MongoDB Version
        run: mongod --version
